#!/usr/bin/env bash

# Deploy the application by pushing files to gh-pages

CSS_PATH='css'
IMG_PATH='images'
TAR_PATH='target'

#   1. Build the application (This is done automaticall by Atom)
# elm-make src/Main.elm --output $OUT_PATH

#   2. Push to gh-pages
mkdir tmp
cp -r $CSS_PATH tmp/
cp -r $IMG_PATH tmp/
cp -r $TAR_PATH tmp/

git checkout gh-pages
cp -rf tmp/* .

git add $CSS_PATH $IMG_PATH $TAR_PATH
git commit -m "Deployed new version to gh-pages!"
git push origin gh-pages

#   3. Clean up
rm -rf tmp
git checkout master
